name: cicd-workflow with slack integration
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_NOTIFICTIONS_URL: ${{ secrets.SLACK_NOTIFICTIONS_URL}}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: API testing 
      run: mvn install -f MyWebApp/pom.xml
    - uses: act10ns/slack@v2
      with:
        channel: '#github-notifications'
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()

